name: "A2C-MLP-Baseline"

# SB3 hyperparameters
verbose: 1
learning_rate: 0.0007
n_steps: 5
gamma: 0.99               # Discount factor (how important is the future)
ent_coef: 0.01            # Entropy coefficient (how much agent should explore)
total_timesteps: 50000
policy_type: "MlpPolicy"  # Policy Network
seed: 42
