pair_selection:
  ps_factor: 0.05
  top_n_factor: 10
  method: "second" # "both" or "second"

  optimization:
    start: "2023-09-01"
    end: "2023-11-01"

  test:
    start: "2023-10-01"
    end: "2023-12-01"

performance:
  window: "static" # "rolling", "static" or "fixed"
  beta_hedge: "static" # "rolling", "static", "no_hedge"
  beta_method: "johansen" # "ols" or "johansen"
  delayed_entry: True # True or False
  time_exit: True # True or False

  iterations: 12 # integer >= 1

  optimization:
    win_start: "2023-11-01"
    start: "2023-12-01"
    end: "2024-01-01"

    # Search parameters
    n_iter: 300
    replicates: 1
    penalty_bad: -100

    # Parameters space
    window_factor_min: 1.50
    window_factor_max: 4.00

    fixed_window_factor_min: 1
    fixed_window_factor_max: 1000

    entry_threshold_min: 2.00
    entry_threshold_max: 4.00

    exit_threshold_min: 0.00
    exit_threshold_max: 1.00

    stop_loss_min: 1.50
    stop_loss_max: 3.00

    # Objective parameters
    min_trades_per_pair: 5

  test:
    win_start: "2023-12-01"
    start: "2024-01-01"
    end: "2024-02-01"
