defaults:
  - override hydra/job_logging: none

hydra:
  run:
    dir: .
  output_subdir: null

wandb:
  project: "research-paper"
  entity: null
  mode: "online"

paths:
  models_dir: models

tickers: [ "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "ADAUSDT", "AVAXUSDT", "DOGEUSDT", "TRXUSDT",
           "DOTUSDT", "LINKUSDT", "SHIBUSDT", "LTCUSDT", "BCHUSDT", "UNIUSDT", "XLMUSDT", "ATOMUSDT", "ICPUSDT",
           "FILUSDT", "LDOUSDT", "APTUSDT", "QNTUSDT", "ARBUSDT", "VETUSDT", "MKRUSDT", "OPUSDT", "NEARUSDT",
           "GRTUSDT", "AAVEUSDT", "ALGOUSDT" ]

market:
  initial_cash: 100000
  fee_rate: 0.001
  risk_free_rate_annual: 0.00
  interval: "1h"

rl:
  seed: 42
  total_timesteps: 1000000
  verbose: 1
