# yaml-language-server: $schema=schemas/schema.json

defaults:
  - override hydra/job_logging: none

hydra:
  run:
    dir: .
  sweep:
    dir: results/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: .
  output_subdir: null

wandb:
  project: "research-paper"
  mode: online

tickers: [ "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "ADAUSDT", "AVAXUSDT", "DOGEUSDT", "TRXUSDT",
           "DOTUSDT", "LINKUSDT", "SHIBUSDT", "LTCUSDT", "BCHUSDT", "UNIUSDT", "XLMUSDT", "ATOMUSDT", "ICPUSDT",
           "FILUSDT", "LDOUSDT", "APTUSDT", "QNTUSDT", "ARBUSDT", "VETUSDT", "MKRUSDT", "OPUSDT", "NEARUSDT",
           "GRTUSDT", "AAVEUSDT", "ALGOUSDT" ]

market:
  initial_cash: 100000
  fee_rate: 0.001
  risk_free_rate_annual: 0.00
  interval: 1h

settings:
  vol_window: 24

  window_min: 48
  window_max: 336

  time_decay_min: 0.5
  time_decay_max: 1.0
