fixed_window: null
entry_threshold: null
exit_threshold: null
stop_loss: null

pair_selection:
  top_n_factor: 20
  coint_type: "eg" # "eg" or "johansen"

  start: "2023-11-01"
  end: "2024-01-01"

performance:
  iterations: 12 # integer >= 1

  beta_method: "kalman" # "ols" or "kalman"
  beta_hedge: "rolling" # "static", "rolling", or "no_hedge"
  window_method: "rolling" # "fixed", "static", or "rolling"

  delayed_entry: True # True or False
  sl_lock: True
  time_decay_start: 0.5
  time_decay_end: 1.0
  rl_reward: "pnl" # "pnl" or "risk_adj"

  vol_window: 24
  window_min: 48
  window_max: 336

  min_trades_per_pair: 10

  optimization:
    objective_func: "sortino" # "sortino"
    metric_type: "net" # "gross" or "net"

    win_start: "2023-11-01"
    start: "2023-12-01"
    end: "2024-01-01"

    # Search parameters
    n_iter: 300
    replicates: 1
    penalty_bad: -100

    # Parameters space
    entry_threshold_min: 1.50
    entry_threshold_max: 3.50

    exit_threshold_min: 0.00
    exit_threshold_max: 0.50

    stop_loss_min: 1.05
    stop_loss_max: 3.00

  test:
    win_start: "2023-12-01"
    start: "2024-01-01"
    end: "2024-02-01"

defaults:
  - _self_
  - base
