# yaml-language-server: $schema=schemas/schema.json

generate_plots: false
save_for_training: false
rl_model_folder: null

pair_selection:
  top_n: 10
  start: 2023-11-01
  end: 2024-01-01

performance:
  use_rl: false

  z_score_window: 672
  entry_threshold: 2.5
  exit_threshold: 0.0
  stop_loss: 2.0

  iterations: 12
  beta_hedge: rolling
  delayed_entry: true
  sl_lock: true
  time_decay_sl: true
  freeze_std: true

  beta_start: 2023-12-01
  start: 2024-01-01
  end: 2024-02-01

defaults:
  - _self_
  - base
