# yaml-language-server: $schema=schemas/schema.json

clean_single_backtests: true
generate_plots: false
save_for_training: false
rl_model_folder: null

pair_selection:
  top_n: 20
  start: 2023-11-01
  end: 2024-01-01

performance:
  use_rl: false
  autonomous_agent: True

  z_score_window: 168
  entry_threshold: 3.0
  exit_threshold: 0.0
  stop_loss: 2.0

  iterations: 12
  beta_hedge: rolling
  delayed_entry: false
  sl_lock: true
  time_decay_sl: true
  freeze_std: true

  beta_start: 2023-12-01
  start: 2024-01-01
  end: 2024-02-01

defaults:
  - _self_
  - base
