# yaml-language-server: $schema=schemas/schema.json

defaults:
  - _self_
  - base
  - rl_algo: recurrent_ppo

rl:
  training_folder: null

  reward: StepPnLReward
  reward_lambda: 1.2
  fee_multiplier: 0.2

  obs_space_type: standard
  passes_per_pair: 20
  seed: 42
  verbose: 1
  freeze_std: true
  time_decay_stop: true
