# yaml-language-server: $schema=schemas/schema.json

defaults:
  - _self_
  - base
  - rl_algo: recurrent_ppo

rl:
  training_subfolder: "WINNER_5_hybrid_fixed"
  reward: pnl_signal
  obs_space_type: minimal
  passes_per_pair: 10
  seed: 42
  verbose: 1
