# yaml-language-server: $schema=../schemas/schema_rl_algo.json

algo_name: recurrent_ppo

params:
  learning_rate: 0.0003
  n_steps: 256
  batch_size: 256
  n_epochs: 10
  gamma: 0.999
  ent_coef: 0.01
  clip_range: 0.2
  policy_kwargs:
    lstm_hidden_size: 128
    n_lstm_layers: 1
    shared_lstm: false
    enable_critic_lstm: true
